# baseURL = "https://EddieAbbondanzio.github.io/"
baseURL = "https://eddieabbondanz.io"
languageCode = "en-us"
title = "Eddie Abbondanzio"
theme = "allegiant"
author = "Eddie Abbondanzio"
copyright = "&copy; 2019. All rights reserved."
canonifyurls = true
paginate = 10

[params]
    ga_api_key = "UA-128571017-1" # Google Analytics API key.
    avatar = "/img/avatar.jpg" # Image should be square, and roughly 150px x 150px
    bio = "My name's Eddie Abbondanzio, and I'm a full time Software Developer. Programming is my favorite hobby, and I love working on anything web related, and my own personal projects. If I'm not programming, then I'm likely working on one of my cars."
    github = "http://github.com/EddieAbbondanzio"
    twitter = "https://twitter.com/EAbbondanzio"

