baseURL = "https://EddieAbbondanzio.github.io/"
languageCode = "en-us"
title = "Eddie Abbondanzio"
theme = "base16"
PygmentsCodeFences = true
PygmentsStyle = "monokai"

[taxonomies]
    category = "categories"
    role = "roles"