# baseURL = "https://EddieAbbondanzio.github.io/"
baseURL = "https://eddieabbondanz.io"
languageCode = "en-us"
title = "Eddie Abbondanzio"
theme = "allegiant"
author = "Eddie Abbondanzio"
copyright = "&copy; 2019. All rights reserved."
canonifyurls = true
paginate = 10

[taxonomies]
    category = "categories"
    tag = "tags"

[params]
    ga_api_key = "UA-128571017-1" # Google Analytics API key.
    avatar = "/img/avatar.jpg" # Image should be square, and roughly 150px x 150px
    bio = "My name's Eddie Abbondanzio, and this is my blog. I mostly write about game dev / web dev, but I'll throw in the occasional car post."
    github = "http://github.com/EddieAbbondanzio"
    twitter = "https://twitter.com/EAbbondanzio"

