name = "BurntToast"
license = "MIT"
description = "A blog theme that supports, series, categories, and tags on posts."
tags = ["blog", "minimalistic", "professional", "development"]
features = ["blog", "tags", "categories"]
min_version = "0.10"

[author]
  name = "Eddie Abbondanzio"
  homepage = "https://github.com/EddieAbbondanzio"
